# @host = http://localhost:5252
@host = https://localhost:7263

### REGISTER
POST {{host}}/auth/register
content-type: application/json

{
  "firstName": "Karol",
  "lastName": "Maj",
  "email": "test@test.com",
  "password": "password"
}

### LOGIN
POST {{host}}/auth/login
content-type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

